# Use postgres/example user/password credentials
version: '3.9'

services:
  web: 

  db:
    image: postgres:14
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
    - "5432:5432" 
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
    - "6380:6379" 

  worker: 
    build: ./project
    command: celery -A worker.celery worker -l info
    volumes:
      -./pomodoro:/code
    environment:
      - CELERY_BROKER_URL=redis://cache:6379/0
      - CELERY_RESULT_BACKEND=redis://cache:6379/0
    depends_on:
      - db
      - cache
